# Generated by Django 5.2.7 on 2025-11-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('failed', 'فاشل'), ('refunded', 'تم الاسترداد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('progress', models.IntegerField(default=0, verbose_name='نسبة الإكمال')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخر دخول')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
