# Generated by Django 5.2.7 on 2025-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.JSONField(default=list, verbose_name='الدروس المكتملة'),
        ),
    ]
