# Generated by Django 5.2.8 on 2025-11-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_completed_lessons'),
        ('students', '0004_remove_walletsettings_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المطلوب شحنه')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('proof_of_payment', models.CharField(blank=True, max_length=255, verbose_name='رابط إثبات الدفع (WhatsApp)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب شحن رصيد',
                'verbose_name_plural': 'طلبات شحن الرصيد',
            },
        ),
    ]
