# Generated by Django 5.2.7 on 2025-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='رقم الهاتف')),
                ('parent_phone', models.CharField(max_length=11, verbose_name='رقم ولي الأمر')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('residence', models.CharField(max_length=100, verbose_name='محل الإقامة')),
                ('grade', models.CharField(choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة الدراسية')),
                ('year', models.CharField(choices=[('first', 'الأول'), ('second', 'الثاني'), ('third', 'الثالث'), ('fourth', 'الرابع'), ('fifth', 'الخامس'), ('sixth', 'السادس')], max_length=10, verbose_name='الصف/السنة')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رصيد المحفظة')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المنصرف')),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رصيد الإهداءات')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='الصورة الشخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
