# Generated by Django 5.2.7 on 2025-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instapay_number', models.CharField(default='01090801009', max_length=20)),
                ('vodafone_number', models.CharField(default='01002150057', max_length=20)),
                ('etisalat_number', models.CharField(default='01000000000', max_length=20)),
                ('orange_number', models.CharField(default='01111111111', max_length=20)),
                ('whatsapp_number', models.CharField(default='01002150057', max_length=20)),
                ('video_url', models.URLField(blank=True, default='')),
                ('step1_text', models.TextField(default='قم بتحويل مبلغ الشحن إلى أحد أرقام المحافظ الموجودة بالاعلى')),
                ('step2_text', models.TextField(default='احفظ إيصال الدفع أو التقط صورة له')),
                ('step3_text', models.TextField(default='إضغط على الزر بالاسفل لأرسال الإيصال عبر الواتساب')),
                ('step4_text', models.TextField(default='سيتم شحن رصيدك خلال ٢٤ ساعة عمل')),
            ],
            options={
                'verbose_name': 'إعدادات المحافظ',
                'verbose_name_plural': 'إعدادات المحافظ',
            },
        ),
    ]
