# Generated by Django 5.2.8 on 2025-11-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_walletsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletsettings',
            name='video_url',
        ),
    ]
