# Generated by Django 5.2.7 on 2025-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admins/')),
                ('permissions', models.CharField(choices=[('student_manager', 'مشرف الطلاب'), ('teacher_manager', 'مشرف المعلمين'), ('course_manager', 'مشرف الكورسات'), ('support_manager', 'مشرف الدعم الفني'), ('super_admin', 'المدير العام')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
