# Generated by Django 5.2.7 on 2025-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_result_duration_minutes_result_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
