# Generated by Django 5.2.8 on 2025-11-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='notification_sent',
        ),
    ]
