# Generated by Django 5.2.7 on 2025-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('bio', models.TextField(verbose_name='السيرة الذاتية')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('teaching_levels', models.CharField(help_text='اختر المراحل التي تدرسها (اضغط Ctrl لاختيار أكثر من واحدة)', max_length=100, verbose_name='المراحل التعليمية')),
                ('experience', models.TextField(verbose_name='الخبرات السابقة')),
                ('degree', models.CharField(choices=[('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المؤهل العلمي')),
                ('major', models.CharField(max_length=100, verbose_name='التخصص الدقيق')),
                ('certificates', models.TextField(blank=True, verbose_name='الشهادات الإضافية')),
                ('profile_image', models.ImageField(default='default_profile.jpg', upload_to='teachers/profiles/', verbose_name='الصورة الشخصية')),
                ('certificate_image', models.ImageField(default='default_certificate.jpg', upload_to='teachers/certificates/', verbose_name='صورة الشهادة')),
                ('profit_percentage', models.IntegerField(default=50, verbose_name='نسبة الأرباح')),
                ('payment_method', models.CharField(choices=[('vodafone_cash', 'فودافون كاش'), ('insta_pay', 'انستا باي')], max_length=20, verbose_name='طريقة الاستلام')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب/المحفظة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمين',
            },
        ),
    ]
