# Generated by Django 5.2.7 on 2025-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('financial', 'تقرير مالي'), ('students', 'تقرير الطلاب'), ('teachers', 'تقرير المعلمين'), ('courses', 'تقرير الكورسات')], max_length=20, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('data', models.JSONField(verbose_name='بيانات التقرير')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
    ]
