# Generated by Django 5.2.7 on 2025-11-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكورس')),
                ('description', models.TextField(verbose_name='وصف تفصيلي')),
                ('category', models.CharField(max_length=100, verbose_name='التصنيف والتخصص')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الكورس')),
                ('image', models.ImageField(upload_to='courses/images/', verbose_name='الصورة الرئيسية')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'English')], max_length=20, verbose_name='لغة العرض')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('disabled', 'معطل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('estimated_duration', models.CharField(max_length=100, verbose_name='المدة الزمنية المقدرة')),
                ('prerequisites', models.TextField(blank=True, verbose_name='المتطلبات المسبقة')),
                ('teacher_percentage', models.IntegerField(choices=[(50, '50% - حتى 50 طالب'), (60, '60% - من 51 إلى 100 طالب'), (70, '70% - أكثر من 100 طالب')], default=50, verbose_name='نسبة المعلم')),
                ('students_count', models.IntegerField(default=0, verbose_name='عدد الطلاب المسجلين')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوحدة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الوحدة')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب الوحدة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'وحدة دراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('lesson_type', models.CharField(choices=[('video', 'درس فيديو'), ('text', 'مواد نصية'), ('file', 'ملفات مرفقة'), ('project', 'مشروع تطبيقي'), ('resource', 'موارد إضافية')], max_length=20, verbose_name='نوع الدرس')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى النصي')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, verbose_name='YouTube Video ID')),
                ('encrypted_video_id', models.TextField(blank=True, verbose_name='معرف الفيديو المشفر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='courses/attachments/', verbose_name='ملف مرفق')),
                ('external_link', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب الدرس')),
                ('duration', models.IntegerField(default=0, verbose_name='مدة الدرس (دقائق)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order'],
            },
        ),
    ]
