# Generated by Django 5.2.7 on 2025-11-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_type',
            field=models.CharField(choices=[('admin', 'الإدارة'), ('teacher', 'المعلم'), ('student', 'الطالب'), ('all_students', 'كل الطلاب'), ('course_students', 'طلاب كورس محدد')], max_length=20),
        ),
    ]
