# Generated by Django 5.2.7 on 2025-11-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_admin_options_alter_admin_password'),
        ('messaging', '0003_alter_notification_options'),
        ('students', '0002_alter_student_password'),
        ('teachers', '0002_alter_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_admin', to='admins.admin', verbose_name='المستقبل (إدارة)'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_student', to='students.student', verbose_name='المستقبل (طالب)'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages_teacher', to='teachers.teacher', verbose_name='المستقبل (معلم)'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.admin', verbose_name='المرسل (إدارة)'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='المرسل (طالب)'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='المرسل (معلم)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.admin', verbose_name='المستخدم (إدارة)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='المستخدم (طالب)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المستخدم (معلم)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'sender_id'], name='messaging_m_sender__6a4fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver_type', 'receiver_id'], name='messaging_m_receive_51c46a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'created_at'], name='messaging_m_is_read_0c5cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expires_at'], name='messaging_m_expires_e611f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_type', 'user_id', 'is_read'], name='messaging_n_user_ty_3678c2_idx'),
        ),
    ]
