# Generated by Django 5.2.7 on 2025-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_receiver_admin_message_receiver_student_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__6a4fc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_receive_51c46a_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_is_read_0c5cc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_expires_e611f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='messaging_n_user_ty_3678c2_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_admin',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_teacher',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_admin',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_teacher',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_admin',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_student',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_teacher',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
