# Generated by Django 5.2.7 on 2025-11-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_admin_options_alter_admin_password'),
        ('messaging', '0005_remove_message_messaging_m_sender__6a4fc0_idx_and_more'),
        ('students', '0002_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_admin', to='admins.admin'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_admin', to='admins.admin'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_type',
            field=models.CharField(choices=[('admin', 'الإدارة'), ('student', 'طالب'), ('all_students', 'كل الطلاب'), ('course_students', 'طلاب كورس محدد')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('admin', 'الإدارة'), ('student', 'طالب')], max_length=20),
        ),
    ]
